tillioss/tilli-web-app

README.md, package.json, src/Screens/Dashbord.js, src/Screens/LanguageSelect.js, src/config/MyConstant.js
=> language data loading issue fixed

package.json
=> unused code is removed from packagejson file

src/App.js, src/Component/AudioRecognize.js
=> unused codes are removed

src/index.js, src/pages/ModuleScreen.js, src/pages/ParentOnboardingScreen.js, src/pages/ParentScreen.js, src/pages/ParentsHomeScreen.js, src/pages/ProfileScreen.js, src/pages/TilliGameWeb.js, src/pages/tilli-game-web/CreateProfile.js, src/pages/tilli-game-web/GamePlay.js, src/pages/tilli-game-web/GameRoute.js, src/pages/tilli-game-web/LanguageScreen.js, src/pages/tilli-game-web/Login.js, src/pages/tilli-game-web/ParentPasswordSetup.js, src/pages/tilli-game-web/RegisterScreen.js, src/pages/tilli-game-web/SplashScreen.js, src/redux/actions/languageActions.js, src/redux/reducers/languageReducer.js, src/redux/store/index.js
=> alt text has been added for img tags and unused values removed

src/Component/Themes/StoryCardScreen.js, src/Screens/ModuleManager/Themes/DropToSelection.js, src/Screens/ModuleManager/Themes/ImageWithThinking.js, src/Screens/ModuleManager/Themes/IntroducePersons.js, src/Screens/ModuleManager/Themes/MeetSinglePerson.js, src/Screens/ModuleManager/Themes/QuestionsList.js, src/Screens/ModuleManager/Themes/SingleTextImage.js, src/Screens/ModuleManager/Themes/StoryCardScreen.js, src/Screens/NotFoundPage.js, src/Screens/QrCode.js, src/Screens/QrCodeScan.js, src/Screens/SignUp.js, src/pages/ProfileScreen.js
=> Link tags added and return values are added for map functions

src/Screens/LanguageSelect.js, src/Screens/Login.js, src/Screens/Manage.js, src/Screens/ModuleManager/GodotPlay.js, src/Screens/ModuleManager/GodotRedirect.js
=> Unused variables removed, alt attributes added for images, values returned for map functions

src/Screens/ModuleManager/ModuleScreenMange.js, src/Screens/ModuleManager/ThemeViewer.js, src/TilliYourWinning/WinningPage2.js
=> User Action text capture is done

src/Screens/ModuleManager/GodotPlay.js, src/Screens/ModuleManager/ModuleScreenMange.js, src/Screens/ModuleManager/ModuleScreen_2.js, src/Screens/ModuleManager/ThemeViewer.js, src/Screens/ModuleManager/Themes/AudioQuizScreen.js, src/Screens/ModuleManager/Themes/DropToSelection.js, src/config/Common.js
=> Dynamic theme capture function updated

.github/workflows/ci.yml
1. [x] Does your submission pass tests?
2. [x] Have you lint your code locally before submission?
=> Add a build job to the github workflow

README.md
=> Add slack invite link to the readme

README.md
=> Add the CI action status to the read me

src/Screens/ModuleManager/ModuleScreenMange.js, src/config/MyConstant.js
=> function implemented

src/Component/DropDown.js
=> Improve the code formatting of the dropdown component

src/config/Common.js
successfully removed the commented-out code fix #51
=> Remove the commented-out code snippets from the common config #51

src/Component/DropDown.js, src/Component/Themes/ChooseCheckboxQuestions.js
=> Remove commented lines ChooseCheckboxQuestions.js

src/Screens/Dashbord_1.js, src/config/Common.js
successfully removed the commented-out code (fix #44)
=> Remove the commented-out code snippets from the dashboard component #44

.github/ISSUE_TEMPLATE/feature_request.md
Fixes #41  
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
1. [ x] Does your submission pass tests?
2. [ x] Have you lint your code locally before submission?
=> Added issue template

src/Component/TilliGameWebDropDown.js
successfully removed the commented code (fix #43)
=> Remove the commented custom styles code from the dropdown #43

src/redux/reducers/languageReducer.js
* [ yes] Have you followed the guidelines in our Contributing document?
* [ yes] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
=> Removed commented code from languageReducer.js

src/redux/store/index.js
* [ yes] Have you followed the guidelines in our Contributing document?
* [ yes] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
=> removed commented code

src/Component/Themes/Success.js
#73 
removed the commented-out code from Success.js
=> removed commented-out the commented-out in Success.js

src/pages/Footer.js
comments have been removed from the footer.js file
Fix #76
=> removed the comments from footer.js

src/Component/Themes/AudioQuizScreen.js
successfully removed the commented out code from the .js file (fixes the issue #57 )
=> Remove commented-out lines AudioQuizScreen.js (fixes issues #57)

src/pages/TilliGameWeb.js
=> Remove the commented-out code snippets in the TilliGameWeb.js

src/pages/TrackProgressScreen.js
Fix #80 by removing all the commented code lines
=> Removed Commented code lines

src/Component/DropDown.js, src/pages/Footer_2.js
=> Remove the commented-out code snippets in the Footer_2.js

src/pages/ModuleScreen.js
=> Removed Commented Code snippets from pages/ModuleScreen.js

src/Component/Themes/StoryCardScreen.js
* [ x] Have you followed the guidelines in our Contributing document?
* [ x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ x] Have you successfully run tests with your changes locally?
=> Remove comments in StoryCardScreen

src/Component/Themes/DropToSelectionNew.js
=> Removed Commented Code From Component\Themes\DropToSelectionNew.js

src/Component/Themes/QuestionsList.js
fixes #71 
Please review this new PR, if any problem let me know!
=> Made requested changes to QuestionsList.js

src/Component/DropDown.js, src/Component/Themes/ImageWithThinking.js
=> Remove the commented-out code snippets in the ImageWithThinking.js

src/Component/DropDown.js, src/Component/Themes/CircleWithInfoAnimations.js
=> Remove the commented-out code snippets in the CircleWithInfoAnimations.js

src/Screens/Menu/SideMenu.js, src/Screens/Menu/TopMenu.js
=> Remove commented out code from files in /src/Screens/Menu/

src/Screens/ModuleManager/Themes/AudioQuizScreen.js
=> Remove commented out code from AudioQuizScreen.js

src/Screens/Theme.js
=> Remove the commented out code from Theme.js

src/Screens/LevelManager.js
=> Remove commented out code from LevelManager.js

src/Screens/ImageManager.js
=> Remove commented out code from ImageManager.js

src/Screens/Level.js
=> Remove commented out code from Level.js

src/Screens/ModuleManager/Themes/MeetSinglePerson.js
=> Remove commented out code from MeetSinglePerson.js

src/Component/Themes/DropToSelection.js
This PR removes all residual commented-out code blocks from the DropToSelection.js component, as requested in issue #67. Cleaning up these dead snippets improves code readability and reduces maintenance overhead.
=> Remove commented-out code in DropToSelection.js (#67)

src/redux/actions/index.test.js, src/redux/actions/languageActions.test.js, src/redux/reducers/authReducer.test.js, src/redux/reducers/gameAuthReducer.test.js, src/redux/reducers/index.test.js, src/redux/reducers/languageReducer.test.js, src/redux/reducers/loginReducer.test.js, src/redux/reducers/signUpReducer.test.js, src/redux/reducers/userInfoReducer.test.js, src/redux/store/index.test.js
__ All Submissions:
Fixes #125
=> Unit tests for Redux actions, reducers & store

package-lock.json, package.json, src/Screens/ModuleManager/Themes/AskAge.js, src/Screens/ModuleManager/Themes/AskAge.test.js, src/Screens/ModuleManager/Themes/AskGender.js, src/Screens/ModuleManager/Themes/AskGender.test.js, src/Screens/ModuleManager/Themes/AudioQuizScreen.js, src/Screens/ModuleManager/Themes/AudioQuizScreen.supported.test.js, src/Screens/ModuleManager/Themes/AudioQuizScreen.test.js, src/Screens/ModuleManager/Themes/ChooseCheckboxQuestions.js, src/Screens/ModuleManager/Themes/ChooseCheckboxQuestions.test.js, src/Screens/ModuleManager/Themes/CircleWithInfoAnimations.js, src/Screens/ModuleManager/Themes/CircleWithInfoAnimations.test.js, src/Screens/ModuleManager/Themes/DoubleBoxOverlapWithImage.test.js, src/Screens/ModuleManager/Themes/DoubleBoxUnderWithImage.js, src/Screens/ModuleManager/Themes/DoubleBoxUnderWithImage.test.js, src/Screens/ModuleManager/Themes/ImageWithThinking.test.js, src/Screens/ModuleManager/Themes/IntroducePersons.js, src/Screens/ModuleManager/Themes/IntroducePersons.test.js, src/Screens/ModuleManager/Themes/MeetSinglePerson.js, src/Screens/ModuleManager/Themes/MeetSinglePerson.test.js, src/Screens/ModuleManager/Themes/PersonWithTextAnimation.js, src/Screens/ModuleManager/Themes/PersonWithTextAnimation.test.js, src/Screens/ModuleManager/Themes/QuestionsList.test.js, src/Screens/ModuleManager/Themes/SingleTextImage.test.js, src/Screens/ModuleManager/Themes/StoryCardScreen.test.js, src/Screens/ModuleManager/Themes/Success.js, src/Screens/ModuleManager/Themes/Success.test.js, src/setupTests.js
=> Tests for untested themes sub components under ModuleManager
